"""added m2m pages_tages

Revision ID: 4bb12bf77f8b
Revises: 72d08f7c6d63
Create Date: 2025-04-26 11:21:57.549668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb12bf77f8b'
down_revision: Union[str, None] = '72d08f7c6d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages_tages',
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('page_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_tages')
    # ### end Alembic commands ###
