"""fix m2m for pages_tags

Revision ID: 76027e79682f
Revises: db9885f66647
Create Date: 2025-04-26 13:32:30.221511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76027e79682f'
down_revision: Union[str, None] = 'db9885f66647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages_tags',
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', 'tag_id')
    )
    op.drop_table('pages_tages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages_tages',
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name='pages_tages_page_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='pages_tages_tag_id_fkey'),
    sa.PrimaryKeyConstraint('page_id', 'tag_id', name='pages_tages_pkey')
    )
    op.drop_table('pages_tags')
    # ### end Alembic commands ###
