"""added server_default and index for datetime fields

Revision ID: 870e2bca0d12
Revises: 2e853ff5aa79
Create Date: 2025-05-09 20:29:57.060838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870e2bca0d12'
down_revision: Union[str, None] = '2e853ff5aa79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pages_followers_created_at'), 'pages_followers', ['created_at'], unique=False)
    op.create_index(op.f('ix_pages_requests_created_at'), 'pages_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_pages_requests_created_at'), table_name='pages_requests')
    op.drop_index(op.f('ix_pages_followers_created_at'), table_name='pages_followers')
    # ### end Alembic commands ###
