"""added fks into pages_tages

Revision ID: db9885f66647
Revises: 4bb12bf77f8b
Create Date: 2025-04-26 11:33:52.122154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9885f66647'
down_revision: Union[str, None] = '4bb12bf77f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pages_tages', 'pages', ['page_id'], ['id'])
    op.create_foreign_key(None, 'pages_tages', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages_tages', type_='foreignkey')
    op.drop_constraint(None, 'pages_tages', type_='foreignkey')
    # ### end Alembic commands ###
