"""added roll to user model

Revision ID: f9dce85c169f
Revises: 3423912e7e85
Create Date: 2025-04-27 12:54:10.887920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9dce85c169f'
down_revision: Union[str, None] = '3423912e7e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roll', sa.Enum('USER', 'ADMIN', 'MODERATOR', 'GUEST', name='roleenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roll')
    # ### end Alembic commands ###
